- Reintegrated PDM-branch (switch to USE Version 4)
git-svn-id: https://db-svn.informatik.uni-bremen.de/repos/stuff/use/trunk@5494 e95982d2-0d12-e879-a455-8ce5a0885042

diff --git a/bin/use b/bin/use
--- a/bin/use
+++ b/bin/use
@@ -1,50 +1,21 @@
 #!/bin/sh
 #
-# $ProjectHeader: use 0.393 Wed, 16 May 2007 14:10:28 +0200 opti $ 
 # Start script for USE
 
-## resolve links - $0 may be a link to use home
-PRG="$0"
-progname=`basename "$0"`
+# CONFIGURATION
+# Add -Xss20m to VMARGS when using the generator
+VMARGS=""
 
-# need this for relative symlinks
-while [ -h "$PRG" ] ; do
-  ls=`ls -ld "$PRG"`
-  link=`expr "$ls" : '.*-> \(.*\)$'`
-  if expr "$link" : '/.*' > /dev/null; then
-  PRG="$link"
-  else
-  PRG=`dirname "$PRG"`"/$link"
-  fi
-done
+BIN_DIR="$( cd "$( dirname "$0" )" && pwd )"
+USE_HOME="$BIN_DIR/.."
+USE_JAR="$USE_HOME/lib/use.jar"
 
-USE_HOME=`dirname "$PRG"`/..
-
-# make it fully qualified
-# unset CDPATH since the bash cd builtin may print the result in some cases,
-# and we get the path twice. 
-unset CDPATH
-USE_HOME=`cd "$USE_HOME" && pwd`
-
-basedir=$USE_HOME
-
-# build classpath and path for native readline library wrapper
-# if we have a build directory then use libraries from current build, 
-# otherwise use released libraries
-
-if [ -d $basedir/build ]; then
-    CLASSPATH=`echo $basedir/build/lib/*.jar | sed s/\ /:/g`
-    LD_LIBRARY_PATH=$basedir/build/lib
-else
-    CLASSPATH=`echo $basedir/lib/*.jar | sed s/\ /:/g`
-    LD_LIBRARY_PATH=$basedir/lib
+if [ ! -f "$USE_JAR" ]; then
+	echo "Cannot find USE executable. Please provide correct path to use.jar." >&2
+	exit 1
 fi
-export CLASSPATH LD_LIBRARY_PATH
+
+LD_LIBRARY_PATH="$USE_HOME/lib"
 
 # set cmd for running USE
-cmd="java -Xms128m -Xmx512m org.tzi.use.main.Main -H=$basedir $@"
-
-# run the java vm
-exec $cmd
-
-
+java $VMARGS -jar "$USE_JAR" "$@"
